server/src/auth-user/auth-user.controller.ts

[fix]リクエストURLのバージョン分けをした

---

server/front/src/App.vue
server/front/src/router.ts
server/front/src/views/Login.vue

/loginで接続できるログイン・サインアップページ作成し、ヘッダーにlocalhost:3000/auth-ser/v1へ飛ぶボタンを配置した
なし
なし
なし

ログイン・サインアップページ作成

---

docker-compose.yml
server/front/.eslintrc.js
server/front/package-lock.json
server/front/package.json
server/front/src/adapters/ApiClient.ts
server/front/src/utils/EnvManager.ts
server/front/tests/unit/example.spec.ts

ApiClientを実装
ApiClientのtestコードを書いた
サーバーURLを環境変数から参照できるように
EnvManagerで環境変数管理できるように
なし
npm iでライブラリを更新してください
なし

サーバーとやり取りするためのApiClientを実装

---

server/package-lock.json
server/package.json
server/src/app.module.ts
server/src/main.ts
server/src/user/user.controller.spec.ts
server/src/user/user.controller.ts
server/src/user/user.module.ts
server/src/user/user.service.spec.ts
server/src/user/user.service.ts

nestjs/typeormのインストール
nestjs/typeormの設定
実際に使ってみた例を記載
なし
npm i
なし

nestjsでどこからでもtypeormを呼び出せるように設定しデモを実装

---

server/src/application/user/user.controller.spec.ts
server/src/domain/user/user.service.spec.ts

[chore]テストが通るように修正

---

server/front/src/infrastructure/httpAdapters/ApiClient.ts
server/front/tests/unit/example.spec.ts

[refactor]フォルダ整理と各種作成

---

Makefile

[chore]makefile作成

---

server/src/domain/entities/user.entity.ts
server/src/domain/user/user.dto.ts
server/src/domain/user/user.service.ts
server/src/infrastructure/db/migrations/1569399306645-user.ts

dbの更新が必要なので make migrate_upしてください

[chore]userテーブルのstudentNumberをoicNumberに変更

---

server/src/application/user/user.controller.ts
server/src/domain/user/user.service.ts

[feat]GET user/v1/:idでユーザIDからユーザを返す

---

server/front/src/views/TopPage.vue

top page layout

---

server/src/domain/entities/following.entity.ts
server/src/domain/entities/user.entity.ts
server/src/infrastructure/db/migrations/1569913449350-followings.ts

[feat]followingテーブルを作成

---

server/front/src/views/UserInitProfilePage.vue

[design]空白の削除

---

server/src/application/user/user.controller.ts
server/src/domain/entities/user.entity.ts
server/src/domain/user/user.dto.ts
server/src/domain/user/user.service.ts
server/src/infrastructure/auth-user/auth-user.module.ts
server/src/infrastructure/strategy/jwt.strategy.ts
server/src/infrastructure/user/user.module.ts

[feat]ユーザー登録時にjwtを要求する

---

server/front/src/views/FollowListPage.vue

final for followlistpage

---

server/src/app.module.ts
server/src/application/auth-user/auth-user.controller.spec.ts
server/src/application/auth-user/auth-user.controller.ts
server/src/application/user/user.controller.ts
server/src/domain/auth-user/services/user-exist.service.ts
server/src/infrastructure/auth-user/auth-user.module.ts
server/src/infrastructure/auth-user/strategies/google.strategy.ts

google認証時に、作成されてないユーザなら、ユーザープロフィール初期設定ページへリダイレクトする。作成されてたらタイムラインページへ

---

server/src/app.module.ts
server/src/application/user/user.controller.spec.ts
server/src/application/user/user.controller.ts
server/src/domain/user/follow-result.ts
server/src/domain/user/user.service.spec.ts
server/src/domain/user/user.service.ts
server/src/infrastructure/user/user.module.ts

[feat] フォロー、フォロー解除の実装

---

server/front/src/views/TimelinePage.vue

[design]タイムラインのレイアウトを作成

---

server/front/src/views/TopPage.vue

トップページにログイン/サインアップボタンを作って、ボタンを押したらlocalhost:3000/auth-user/v1に遷移するようにすた

---

server/front/src/views/EditProfilePage.vue

[design] edit-profile page 完了かな確認要

---

server/front/package-lock.json
server/front/package.json

Cookieのライブラリをセットアップした
なし
なし
なし

[chore]Cookieのライブラリをセットアップした

---

server/front/.gitignore
server/front/.vscode/settings.json
server/front/tests/unit/example.spec.ts

フロントのテスト通るようにした。後環境とか使いやすくした

---

server/front/src/application/LoginApplication.ts
server/front/src/create/CreateLoginInfoApplication.ts
server/front/src/domain/login/LoginInfoRepository.ts
server/front/src/infrastructure/login/LoginInfoRepositoryImpl.ts
server/front/tests/unit/example.spec.ts

[feat]jwtからログイン中か判定する機能実装

---

server/front/components/Footer.vue

[feat] ProfileボタンとTimelineボタンを機能させました。

---

server/front/components/Post.vue
server/front/src/views/TimelinePage.vue

投稿（タイムラインやプロフィールに使う奴）のコンポーネントを作成した。

[feat]投稿のレイアウトのコンポーネントを作成した

---

server/front/components/Footer.vue

[feat] ログイン中じゃなければfooterを表示しないようにしました

---

server/front/src/application/UserApplication.ts
server/front/src/create/CreateUserApplication.ts
server/front/src/domain/user/MakeUserResult.ts
server/front/src/domain/user/Sex.ts
server/front/src/domain/user/UserDto.ts
server/front/src/domain/user/UserId.ts
server/front/src/domain/user/UserRepository.ts
server/front/src/infrastructure/user/UserRepositoryImpl.ts
server/front/src/router.ts
server/front/src/views/UserInitProfilePage.vue

ユーザの新規作成の処理を外側だけ実装

---

server/src/infrastructure/auth-user/strategies/google.strategy.ts

グーグル認証でアカウント選択がスキップされる問題を修正

---

server/src/domain/entities/post.entity.ts
server/src/domain/entities/user.entity.ts
server/src/infrastructure/db/migrations/1570768335069-post.ts

[feat]Postテーブルつくた

---

server/front/src/views/TimelinePage.vue

[feat]投稿ボタン押したら投稿フォームが表示するようにしました

---

server/front/src/application/UserApplication.ts
server/front/src/components/Footer.vue
server/front/src/domain/user/UserRepository.ts
server/front/src/infrastructure/user/UserRepositoryImpl.ts

Profileボタン押したら自分のuserIdのuserページへ遷移できる機能追加

---

server/src/app.module.ts
server/src/application/post/post.controller.ts
server/src/domain/entities/post.entity.ts
server/src/domain/post/post.dto.ts
server/src/domain/post/responce/post.result.ts
server/src/domain/post/service/post.service.ts
server/src/infrastructure/post/post.module.ts

[feat]投稿機能の実装

---

server/src/application/user/user.controller.ts
server/src/domain/user/response/my-user-responcse.ts
server/src/domain/user/user.service.ts

[feat]my_userの実装

---

server/front/package-lock.json
server/front/package.json
server/front/src/views/UserPage.vue

title not yet

---

server/src/app.module.ts
server/src/application/post/post.controller.ts
server/src/application/timeline/timeline.controller.ts
server/src/domain/timeline/timeline.service.ts
server/src/infrastructure/timeline/timeline.module.ts

[feat]最新10件の投稿を返す

---

server/front/src/infrastructure/httpAdapters/ApiClient.ts
server/front/src/infrastructure/httpAdapters/Protocol.ts
server/front/src/infrastructure/user/UserRepositoryImpl.ts
server/front/src/views/UserInitProfilePage.vue
server/src/main.ts

[feat]ユーザーの新規登録のrepositoryを実装した

---

server/front/src/infrastructure/httpAdapters/ApiClient.ts
server/src/domain/entities/user.entity.ts
server/src/domain/user/user.dto.ts
server/src/infrastructure/db/migrations/1570996796235-user-birthday.ts
server/src/main.ts

birthdayのカラムをnull許容に

---

server/src/application/user/user.controller.ts
server/src/domain/user/response/find-user-response.ts
server/src/domain/user/user.service.ts

[feat]ユーザ検索時、自分自身か否かの情報を付随するように

---

server/front/src/infrastructure/httpAdapters/ApiClient.ts
server/front/src/infrastructure/user/UserRepositoryImpl.ts

Profileボタン押したら、jwtから自身のUserIdをサーバから取得し、正しい自分自身のユーザページへ遷移するようにする

Profileボタン押したら、jwtから自身のUserIdをサーバから取得し、正しい自分自身のユーザページへ遷移するようにする

---

server/src/domain/post/service/post.service.ts

[feat]投稿に失敗した場合例外を投げるように

---

server/src/domain/user/user.dto.ts
server/src/domain/user/user.service.ts

[feat]oicNumberをgoogle認証により自動設定するように

---

server/front/src/application/PostApplication.ts
server/front/src/create/CreatePostApplication.ts
server/front/src/domain/post/CreatePostParams.ts
server/front/src/domain/post/CreatePostResult.ts
server/front/src/domain/post/PostRepository.ts
server/front/src/infrastructure/post/PostRepositoryImpl.ts
server/front/src/views/TimelinePage.vue

[feat]仮の投稿機能を作りました

---

server/front/src/infrastructure/httpAdapters/ApiClient.ts
server/src/domain/entities/user.entity.ts
server/src/domain/user/user.dto.ts
server/src/infrastructure/db/migrations/1571339236258-user-note.ts

userテーブルのnoteカラムをデフォルト空文字に

---

server/front/src/App.vue

ログインしていない場合topとログインする画面に行けないようにした

ログイン中でない場合topページへリダイレクトするようにした

---

server/front/src/infrastructure/httpAdapters/ApiClient.ts

ユーザ作成リクエストにoicNumberの送信を削除

---

server/front/src/views/UserPage.vue

フォロー・フォローリストボタンの位置をセンターに移動

---

server/front/src/components/FollowUser.vue
server/front/src/views/FollowListPage.vue

[feat]フォローユーザのコンポーネント化

---

server/front/src/components/PostList.vue
server/front/src/views/TimelinePage.vue

[feat]投稿一覧リストをコンポネント化しました

---

server/src/application/user/user.controller.spec.ts
server/src/domain/google-profiles.repository.ts
server/src/domain/user/user.service.spec.ts
server/src/domain/user/user.service.ts
server/src/infrastructure/auth-user/strategies/google.strategy.ts
server/src/infrastructure/temp-data/google.profiles.data.ts
server/src/infrastructure/user/user.module.ts

googleProfilesDataの依存を分離

---

server/front/package-lock.json
server/front/src/components/Footer.vue

[feat] footerのボタンをiconに変更

---

server/front/src/views/UserPage.vue

[feat] followlistへの遷移は完成

---

server/front/src/application/PostApplication.ts
server/front/src/components/PostList.vue
server/front/src/domain/post/PostRepository.ts
server/front/src/infrastructure/httpAdapters/ApiClient.ts
server/front/src/infrastructure/post/PostRepositoryImpl.ts

[feat]タイムラインページで最新の投稿10件を取得して表示できるようにしました

---

server/front/src/share/test.ts
server/tsconfig.json

[chore]serverはfrontのdomainを参照できるように

---

server/front/src/App.vue
server/front/src/components/PostList.vue
server/front/src/views/FollowListPage.vue
server/front/src/views/TopPage.vue
server/front/src/views/UserInitProfilePage.vue
server/front/src/views/UserPage.vue

デザインの軽重な修正と不正なタグの修正

---

server/nodemon.json
server/package.json
server/src/application/timeline/timeline.controller.ts
server/src/domain/timeline/timeline.service.ts
server/src/infrastructure/config/ormconfig.js

[fix]最新の投稿10件を返すレスポンスの修正

---

server/front/src/application/PostApplication.ts
server/front/src/domain/post/CreatePostParamsDto.ts
server/front/src/domain/post/PostRepository.ts
server/front/src/infrastructure/httpAdapters/ApiClient.ts
server/front/src/infrastructure/post/PostRepositoryImpl.ts
server/front/src/views/TimelinePage.vue
server/src/application/post/post.controller.ts
server/src/domain/post/post.dto.ts
server/src/domain/post/responce/post.result.ts
server/src/domain/post/service/post.service.ts

投稿を作成できるように

---

server/front/src/views/UserInitProfilePage.vue

初期プロフィール設定ページのバリデーション処理

---

server/front/src/domain/post/PostId.ts
server/front/src/domain/post/PostInfos.ts
server/front/src/domain/post/SearchPostParamsDto.ts
server/src/application/timeline/timeline.controller.ts
server/src/domain/timeline/timeline.service.ts

過去の投稿を取得できるようにした

---

server/front/src/components/PostList.vue
server/front/src/components/post/OldPostGetButton.vue

[feat]過去の10件の投稿を取得して表示できるように

---

server/front/src/components/PostList.vue
server/front/src/views/UserPage.vue

[feat]ユーザページでページのユーザが投稿した投稿だけ表示

---

package.json
server/front/src/views/TopPage.vue

[chore]デプロイのための環境整備

---

server/front/src/components/PostList.vue

プロトタイプ1　ベータ1.1

---

.circleci/config.yml
server/src/domain/entities/post.entity.ts
server/src/infrastructure/db/migrations/1570768335069-post.ts

[chore]circleCiのmysqlのバージョンをダウングレード

---

server/front/src/components/Footer.vue
server/front/src/components/Post.vue
server/front/src/components/PostList.vue
server/front/src/components/post/NewPostGetButton.vue
server/front/src/domain/post/SearchPostParamsDto.ts
server/src/domain/timeline/timeline.service.ts

]基準の投稿idより新しい投稿を10件取得して表示できるように。あとフッタの遷移高速化

---

server/front/src/components/Footer.vue
server/front/src/views/UserPage.vue

ユーザページからタイムラインページに行けないバグを修正 あとユーザページの変な横幅改善

---

server/front/src/views/TimelinePage.vue
server/src/domain/post/service/post.service.ts

空の投稿をできないようにサーバでブロック

---

server/front/src/components/FollowList/FollowList.vue
server/front/src/components/post/PostForm.vue
server/front/src/utils/AsyncOnce.ts
server/front/src/views/TimelinePage.vue
server/src/application/user/user.controller.ts
server/src/domain/user/user.service.ts

投稿の連続リクエスト禁止と、タイムラインページのリファクタリング

---

server/front/src/components/post/PostForm.vue

空の投稿をできないようにした

---

server/front/src/components/Footer.vue
server/front/src/views/UserInitProfilePage.vue

初期プロフィール設定ページの登録ボタン連続リクエスト禁止 myprofileページへ行くリクエストの連続リクエスト禁止

---

server/front/src/components/FollowList/FollowList.vue
server/front/src/components/FollowList/FollowUser.vue

フォローリストページからフォローしているユーザのページへ行けるように

---

server/front/src/views/FollowListPage.vue

[feat]Follow list page でBACKボタンを押すとユーザーページに戻るようにしました！！

---

server/front/src/components/post/Post.vue
server/front/src/components/post/PostList.vue
server/front/src/views/TimelinePage.vue
server/front/src/views/UserPage.vue

最新の投稿取得ボタンの連打による連続リクエスト禁止

---

server/front/src/infrastructure/httpAdapters/ApiClient.ts
server/front/src/infrastructure/httpAdapters/Protocol.ts
server/front/src/infrastructure/login/LoginInfoRepositoryImpl.ts
server/front/src/infrastructure/post/PostRepositoryImpl.ts
server/front/src/infrastructure/user/UserRepositoryImpl.ts

apiclientインスタンス化時にコンストラクタでjwtをセットできるようにした

---

server/front/src/views/TimelinePage.vue

[feat]投稿後にテキストボックスを空にしました。

---

server/src/application/auth-user/auth-user.controller.ts

[feat]jwtのチェックするだけのリクエスト実装

---

server/front/src/infrastructure/follow-list/FollowListReposioryImpl.ts
server/front/src/infrastructure/post/PostRepositoryImpl.ts
server/src/application/timeline/timeline.controller.ts
server/src/application/user/user.controller.ts

[feat]リソースアクセス系はすべてjwtでguardするように

---

server/front/src/components/post/PostList.vue
server/front/src/components/userPage/UserInfo.vue
server/front/src/views/UserPage.vue

他ユーザページから他のユーザページに移動してもちゃんと反映されるように

---

server/front/src/infrastructure/login/LoginInfoRepositoryImpl.ts

とりあえずcookieの有効期限を15日に設定

---

server/front/src/infrastructure/UnauthorizedErrorHook.ts
server/front/src/infrastructure/follow-list/FollowListReposioryImpl.ts
server/front/src/infrastructure/follow/FollowRepositoryImpl.ts
server/front/src/infrastructure/post/PostRepositoryImpl.ts
server/front/src/infrastructure/user/UserRepositoryImpl.ts

401エラーをキャッチしたら、jwtクリアしつつトップページにリダイレクトするように

---

server/front/src/application/LoginApplication.ts
server/front/src/create/CreateLoginInfoApplication.ts
server/front/src/domain/login/LoginService.ts
server/front/src/infrastructure/UnauthorizedErrorHook.ts
server/front/src/infrastructure/login/LoginInfoRepositoryImpl.ts
server/front/src/infrastructure/login/LoginServiceImpl.ts
server/front/src/views/TopPage.vue

再loginの処理がpwaでもいいかんじになったはず

---

server/front/src/components/post/PostForm.vue

空白、改行だけで構成された投稿は投稿できないようにした

---

server/front/src/application/PostApplication.ts
server/front/src/components/post/PostList.vue
server/front/src/domain/post/PostInfosList.ts

[refactor]投稿一覧クラスを生成して処理を分割した

---

server/front/src/components/userPage/UserInfo.vue

[feat]自身のプローフィルページにプローフィル編集ボタンを追加しました。

---

server/front/src/components/post/Post.vue

投稿の改行に対応した

---

server/front/src/components/userPage/UserInfo.vue

[design]follow/unfollowBtn の色変えたりしました

---

server/src/infrastructure/auth-user/strategies/google.strategy.ts

gmailのバリデーション

---

server/src/domain/entities/course.entity.ts
server/src/domain/entities/study-subject.entity.ts
server/src/domain/entities/user.entity.ts
server/src/infrastructure/db/migrations/1572592931388-user.ts
server/src/infrastructure/db/migrations/1572593941821-user.ts
server/src/infrastructure/db/migrations/1572594101673-user.ts
server/src/infrastructure/db/migrations/1572594682792-user.ts

[feat]ユーザエンティティに新しい項目を追加

---

server/front/src/components/post/Post.vue

[feat]投稿で名前が長すぎの人の表示を省略しました。

---

server/front/src/components/userPage/UserInfo.vue

[feat]自身のプローフィルページにプローフィル編集ボタンを追加しました(他人のページならボタンを表示しないようにした)。

---

server/front/src/views/UserInitProfilePage.vue

ユーザ新規登録ページに学科、専攻、学年、クラス番号を追加し、バリデーションも実装した

---

server/front/package-lock.json
server/front/package.json
server/front/src/components/post/Post.vue

[design]時間の表示を整えた

---

server/src/domain/entities/user.entity.ts
server/src/infrastructure/db/migrations/1572601157410-user.ts

userのカラム名修正

---

server/src/application/post/post.controller.ts
server/src/domain/post/service/post.service.ts

投稿の削除リクエスト実装

---

server/front/package-lock.json
server/front/package.json
server/front/src/components/LogoutBtn.vue
server/front/src/components/userPage/UserInfo.vue
server/front/src/plugins/vuetify.ts

LogoutBtn実装と配置

---

server/front/src/domain/user/UserDto.ts
server/src/domain/entities/user.entity.ts
server/src/domain/user/user.service.ts

返すユーザ情報を追加

---

server/front/package-lock.json
server/front/src/views/TimelinePage.vue

[design]タイムラインページにタイムラインの種別を選ぶタブを追加

---

server/front/package-lock.json
server/package-lock.json
server/package.json
server/src/application/post/post.controller.ts
server/src/domain/post/post.dto.ts
server/src/domain/post/service/post.service.ts
server/src/domain/user/user.dto.ts
server/src/main.ts

なんかバリデーションいっぱい追加した

---

server/front/package-lock.json
server/front/src/components/FollowList/FollowUser.vue
server/front/src/views/FollowListPage.vue

[design]followlistのicon修正完了

---

server/front/package-lock.json
server/front/src/components/userPage/UserInfo.vue

[feat]プロフィールページで資格、マイホームページ、sns、学年、クラス番号、学科、専攻を表示,SNS URL に行けるようにした(完成 )

---

server/package.json
server/src/infrastructure/db/migrations/1572613178878-CourseSeed.ts
server/src/infrastructure/db/migrations/1572615273560-StudySubjectSeed.ts

学科と専攻のシードを用意した

---

server/front/src/domain/course/CourseDto.ts
server/front/src/domain/course/CourseId.ts
server/front/src/domain/studySubject/StudySubjectDto.ts
server/front/src/domain/studySubject/StudySubjectId.ts
server/src/app.module.ts
server/src/application/course/course.controller.ts
server/src/application/study-subject/study-subject.controller.ts
server/src/domain/course/course.service.ts
server/src/domain/study-subject/study-subject.service.ts
server/src/infrastructure/course/course.module.ts
server/src/infrastructure/study-subject/course.module.ts

学科一覧と専攻一覧をサーバから取得できるよ

---

server/front/package-lock.json
server/front/package.json
server/front/src/components/post/Post.vue
server/front/src/plugins/vuetify.ts

[design]Menuボタンの配置とアイコンを決めて、SpeedDialで削除ボタンも追加しました

---

server/front/src/components/post/Post.vue
server/front/src/components/post/PostMenu.vue

postのメニューをコンポーネント化

---

server/front/src/components/post/Post.vue
server/front/src/components/post/PostList.vue
server/front/src/components/post/PostMenu.vue
server/front/src/domain/post/PostInfosList.ts
server/front/src/domain/post/PostRepository.ts
server/front/src/infrastructure/httpAdapters/ApiClient.ts
server/front/src/infrastructure/post/PostRepositoryImpl.ts
server/src/domain/post/service/post.service.ts

投稿削除を実際に機能するように

---

server/front/src/domain/user/MakeUserDto.ts
server/front/src/infrastructure/httpAdapters/ApiClient.ts
server/front/src/infrastructure/httpAdapters/Protocol.ts
server/front/src/infrastructure/user/UserRepositoryImpl.ts
server/front/src/views/UserInitProfilePage.vue

[feat]初期プローフィールページの情報をサーバに送信できるようにしました。(動作確認済)(完成版)

---

server/front/src/domain/category/CategoryDto.ts
server/front/src/domain/category/CategoryId.ts
server/src/app.module.ts
server/src/application/category/category.controller.ts
server/src/domain/category/category.service.ts
server/src/infrastructure/category/category.module.ts

分野種別一覧取得リクエスト実装した

---

server/front/src/domain/user/UserDto.ts
server/src/domain/entities/user.entity.ts
server/src/domain/user/service/user.service.ts
server/src/infrastructure/db/migrations/1573192122019-user-email.ts

ユーザ情報にemailを追加

---

server/front/src/App.vue
server/front/src/components/Drawer.vue
server/front/src/components/LogoutBtn.vue
server/front/src/components/user/UserInfo.vue

[design]navigation-drawerを設定しました

---

server/front/src/domain/user/MyGoogleProfileDto.ts
server/front/src/views/UserInitProfilePage.vue
server/src/infrastructure/temp-data/google.profiles.data.ts

初期プロフィール設定ページで本名を初期値設定するように

---

server/front/src/application/PostApplication.ts
server/front/src/components/post/Post.vue
server/front/src/components/post/PostList.vue
server/front/src/components/post/PostMenu.vue
server/front/src/components/user/UserInfo.vue
server/front/src/domain/post/PostInfos.ts
server/front/src/domain/post/PostInfosList.ts
server/front/src/infrastructure/httpAdapters/ApiClient.ts
server/src/application/timeline/timeline.controller.ts
server/src/domain/timeline/timeline.service.ts

他人の投稿には削除メニューでないように 他にもちょこっと修正

---

server/front/src/domain/post/PostInfosList.ts

投稿配列を非破壊的に操作するように修正

---

server/front/src/views/TimelinePage.vue

timeline使いやすくなった

---

server/front/src/App.vue
server/front/src/views/UserInitProfilePage.vue
server/src/domain/user/service/user.service.ts

自身のユーザが見つからない時はUNAUTHORIZEDエラー扱いにし不正なjwtを許さない

---

server/front/src/components/user/UserInfo.vue

[feat]email欄の追加完成

---

server/front/src/components/user/UserInfo.vue

[feat]profileの自己紹介完成

---

server/front/src/domain/user/UpdateUserDto.ts
server/src/application/user/user.controller.ts
server/src/domain/user/service/user.service.ts
server/src/domain/user/update-user.dto.ts
server/tsconfig.json

ユーザ情報変更リクエストの実装

---

server/front/src/application/PostApplication.ts
server/front/src/components/post/PostForm.vue
server/front/src/views/TimelinePage.vue

軽佻なリファクタリング

---

server/front/package-lock.json
server/front/package.json
server/front/src/App.vue
server/front/src/components/Scroller.vue
server/front/src/views/TimelinePage.vue
server/front/src/views/UserPage.vue

[design]ページ上に戻るボタンの配置確定

---

server/front/src/App.vue
server/front/src/components/Drawer.vue
server/front/src/views/UserPage.vue

design/menu button をuser pageにだけ表示しました

---

server/src/domain/entities/user.entity.ts
server/src/domain/user/make-user.dto.ts
server/src/domain/user/update-user.dto.ts

バリデーション超最強

---

server/front/src/domain/validationRules/EditProfilePageRules.ts
server/front/src/views/EditProfilePage.vue

プロフィール編集ページで学科専攻をサーバから取得

---

server/front/src/views/UserInitProfilePage.vue

初期プロフィール設定ページで学科と専攻正しく入力OK!

---

server/front/src/components/post/PostForm.vue
server/front/src/domain/validationRules/CommonRules.ts
server/front/src/domain/validationRules/PostFormRules.ts

投稿の文字数を255文字に制限をかけカウンターを表示した

---

server/front/src/views/UserPage.vue

自身のユーザページでしかメニュ―を表示しない

---

server/front/src/application/UserApplication.ts
server/front/src/views/EditProfilePage.vue

プロフィール編集で現在の値を初期値として設定するように

---

server/front/package-lock.json
server/front/package.json
server/front/src/App.vue
server/front/src/components/Drawer.vue
server/front/src/components/Scroller.vue
server/front/src/main.ts

一番上へスクロールできた

---

server/front/src/components/Scroller.vue
server/front/src/views/DeleteAccountPage.vue
server/front/src/views/FollowListPage.vue

デザインちょっと修正

---

server/front/src/application/UserApplication.ts
server/front/src/domain/user/UserRepository.ts
server/front/src/infrastructure/httpAdapters/ApiClient.ts
server/front/src/infrastructure/user/UserRepositoryImpl.ts
server/front/src/views/EditProfilePage.vue

プロフィール編集のリクエストを送信するように

---

server/front/src/domain/validationRules/EditProfilePageRules.ts
server/front/src/views/EditProfilePage.vue

プロフィール編集ページのバリデーションを追加

---

server/front/src/views/EditProfilePage.vue

プロフィール編集ページの生年月日入力フォームを変更

---

server/front/src/components/post/PostForm.vue
server/front/src/domain/post/CreatePostParamsDto.ts
server/front/src/views/TimelinePage.vue
server/src/domain/post/post.dto.ts
server/src/domain/post/service/post.service.ts

投稿をカテゴリ選択して投稿できるように

---

server/front/src/views/EditProfilePage.vue

生年月日にバリデーションを施した

---

server/front/src/application/PostApplication.ts
server/front/src/components/post/PostList.vue
server/front/src/domain/post/PostInfosList.ts
server/front/src/domain/post/SearchPostParamsDto.ts
server/front/src/domain/post/TimeLine.ts
server/front/src/views/TimelinePage.vue

タイムラインページで分野種別ごとに投稿絞り込めるように

---

server/front/src/domain/validationRules/CommonRules.ts
server/front/src/views/DeleteAccountPage.vue

[feat]OicNumber確認のやつ作成over

---

server/front/src/components/post/PostList.vue
server/front/src/domain/post/PostInfosList.ts
server/front/src/domain/post/SearchPostParamsDto.ts
server/front/src/domain/post/TimeLine.ts
server/front/src/views/TimelinePage.vue
server/src/domain/timeline/timeline.service.ts

フォローユーザのみ投稿絞り込めるように

---

server/front/src/views/EditProfilePage.vue
server/src/domain/user/service/user.service.ts
server/src/domain/user/update-user.dto.ts

プロフィール編集失敗するのを修正

---

server/front/src/components/user/UserInfo.vue

生年月日の表記を修正

---

server/src/domain/user/service/user.service.ts

ユーザ取得失敗問題修正

---

server/front/src/views/EditProfilePage.vue

プロフィール編集ページの性別を削除

---

server/front/src/components/user/UserInfo.vue
server/front/src/views/EditProfilePage.vue

ホームページurlの文言を修正

---

server/front/src/components/user/UserInfo.vue

大きいサイズならプロフィール詳細を常に表示

---

server/front/src/components/BackBtn.vue
server/front/src/components/post/Post.vue
server/front/src/components/post/PostForm.vue
server/front/src/components/user/UserInfo.vue
server/front/src/plugins/vuetify.ts
server/front/src/views/DeleteAccountPage.vue
server/front/src/views/EditProfilePage.vue
server/front/src/views/FollowListPage.vue
server/front/src/views/TimelinePage.vue

色々デザインレイアウト修正

---

server/front/src/create/CreateLoginApplication.ts
server/front/src/infrastructure/login/LoginRepositoryForPwaImpl.ts

loginデータ扱いの分岐処理を簡潔に

---

server/src/domain/entities/comment.entity.ts
server/src/domain/entities/post.entity.ts
server/src/domain/entities/user.entity.ts
server/src/infrastructure/db/migrations/1575349584391-comment.ts

[feat]create new table to comment.

---

server/front/src/components/comment/Comment.vue
server/front/src/infrastructure/viewData/PostAndCommentViewData.ts

Commentコンポーネントを作成した

---

server/front/src/components/comment/CommentForm.vue
server/front/src/components/post/PostForm.vue
server/front/src/domain/validationRules/PostAndCommentFormRules.ts
server/front/src/domain/validationRules/PostFormRules.ts

コメントフォーム作りました

---

server/front/src/domain/post/CreateCommentParamsDto.ts
server/front/src/domain/post/CreateCommentResult.ts
server/src/application/post/post.controller.ts
server/src/domain/entities/comment.entity.ts
server/src/domain/post/comment.dto.ts
server/src/domain/post/service/comment.service.ts
server/src/domain/post/service/post.service.ts
server/src/infrastructure/db/migrations/1575354694221-comment.ts
server/src/infrastructure/post/post.module.ts

[feat]コメント投稿、削除機能の実装

---

server/front/src/components/comment/CommentForm.vue
server/front/src/components/post/Post.vue
server/front/src/infrastructure/viewData/PostAndCommentViewData.ts

コメントボタンを配置しました

---

server/front/src/components/post/Post.vue
server/front/src/components/post/PostList.vue
server/front/src/views/TimelinePage.vue

コメントボタン押したときに画面を変えることにしました。

---

server/front/src/domain/post/PostInfos.ts
server/src/domain/timeline/timeline.service.ts
server/src/infrastructure/timeline/timeline.module.ts

[feat]コメント数をかえすように

---

server/front/src/components/post/Post.vue

投稿にコメント数表示

---

server/front/src/domain/post/PostInfos.ts
server/src/domain/timeline/timeline.service.ts

投稿データにカテゴリー名を追加

---

server/front/src/components/post/Post.vue

投稿にカテゴリー表示

---

server/front/src/components/post/Post.vue

気に入りボタン配置しました

---

server/front/src/components/post/Post.vue
server/front/src/components/post/PostDetails.vue
server/front/src/components/post/PostList.vue
server/front/src/components/post/PostMenu.vue
server/front/src/views/TimelinePage.vue

[design]投稿詳細コンポーネント作成

---

server/front/src/application/PostApplication.ts
server/front/src/components/post/Post.vue
server/front/src/components/post/PostDetails.vue
server/front/src/components/post/PostList.vue
server/front/src/create/CreatePostApplication.ts
server/front/src/domain/comment/CommentRepository.ts
server/front/src/domain/comment/commentId.ts
server/front/src/domain/post/PostInfosList.ts
server/front/src/domain/post/PostRepository.ts
server/front/src/domain/post/TimeLine.ts
server/front/src/infrastructure/comment/CommentRepositoryImpl.ts
server/front/src/infrastructure/httpAdapters/ApiClient.ts
server/front/src/infrastructure/post/PostRepositoryImpl.ts
server/front/src/views/TimelinePage.vue
server/front/src/views/UserPage.vue

[feat]コメントの機能を実装しました

---

server/front/src/components/post/Post.vue
server/front/src/domain/post/PostInfos.ts
server/src/domain/timeline/timeline.service.ts

[feat]finished like counter position and displaying

---

server/front/src/components/comment/Comment.vue
server/front/src/components/post/PostDetails.vue
server/front/src/views/TimelinePage.vue
server/front/src/views/UserPage.vue

投稿詳細でコメント一覧表示するように

---

server/front/src/views/UserInitProfilePage.vue

初期プロフィール設定ページのタイトル修正

---

server/front/src/domain/post/PostInfosList.ts

コメント数をコメントしたらすぐ反映

---

server/src/domain/post/service/comment.service.ts

[fix]コメント投稿者の名前がおかしいのを修正

---

server/.gitignore
server/front/.firebaserc
server/front/firebase.json
server/front/package-lock.json
server/front/package.json
server/src/main.ts

firebaseセットアップ
